version: "3.8"
services:
  multi-mongo:
    image: mongo:focal
    environment:
      - MONGO_INITDB_ROOT_USERNAME=magdi
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - multi-data:/data/db
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "80:80"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - multi-mongo
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  multi-data: