version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - "80:80"
    depends_on:
      - php
      - mysql
    volumes:
      - ./src:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql:latest
    env_file:
      - ./env/mysql.env
    volumes:
      - data:/var/lib/mysql

  composer:
    build:
      context: .
      dockerfile: dockerfiles/composer.dockerfile
    volumes:
      - ./src:/var/www/html

  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    entrypoint: ['php', '/var/www/html/artisan']
    volumes:
      - ./src:/var/www/html

  npm:
    build:
      context: .
      dockerfile: dockerfiles/npm.dockerfile
    volumes:
      - ./src:/var/www/html
  
volumes:
  data: